# Generated by Django 2.1.9 on 2019-06-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oembed', '0002_auto_20160408_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerrule',
            name='format',
            field=models.IntegerField(choices=[(1, 'JSON'), (2, 'XML')], verbose_name='format'),
        ),
    ]
